name: kasseneck_api
description: "A Flutter package for interacting with the Kasseneck Cashregister API. By Kreiseck."
version: 2.0.0
homepage: https://github.com/mhmmdlkts/kasseneck_flutter_api

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  flutter_blue_plus: ^2.2.1
  esc_pos_utils: ^1.1.0

  sumup: ^0.13.1
    #path: ../sumup_flutter_plugin
  my_pos:
    path: ../mypos_flutter_package/my_pos/my_pos

dependency_overrides:
  image: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0