name: kasseneck_api
description: "A Flutter package for interacting with the Kasseneck Cashregister API. By Kreiseck."
version: 1.1.1
homepage: https://github.com/mhmmdlkts/kasseneck_flutter_api

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  flutter_esc_pos_network: ^1.0.3
  esc_pos_utils_plus: ^2.0.4
  qr_flutter: ^4.1.0
  image: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter: