/// Die Antwortcodeliste von TECS, erhalten ueber hobex am 16.09.2026.
///
/// Das HPS reicht die Codes der TECS-Plattform durch, auf der hobex
/// autorisiert -- laut hobex-Produktmanagement sind sie "aktuell gleich Tecs
/// NaTALI, hier hat sich bei HPS noch nichts geaendert". Gemessen war das
/// schon vorher, ohne dass wir es wussten: `9002`, `9003`, `9011`, `9027`,
/// `9900` und `55` stehen alle in dieser Liste. Die gemessenen Codes stehen
/// weiter in `response_codes.dart`, hier nur die uebrigen.
///
/// **Schreibweise.** TECS fuehrt die ISO-8583-Antworten des Hosts vierstellig
/// (`0055`), das Terminal sendet sie ohne fuehrende Nullen (`55`, gemessen
/// am 02.09.2026). Die Tabelle fuehrt die Form des Terminals; die Abfrage
/// ([HpsCodes.lookup]) findet beide.
///
/// **Einordnung.** Dieselbe Regel wie fuer die HPS-Liste -- entscheidend ist,
/// wo der Code entsteht:
///
/// - Eine **Antwort des Hosts** ohne Genehmigung ist eine Ablehnung: der Host
///   hat geantwortet und nicht autorisiert. `conclusive`.
/// - Eine **Genehmigung, die nicht `0` ist** (`8`, `10`, `11`, `16`, `32`),
///   wird NIE zur Ablehnung: `hostUncertain` mit
///   [HpsCodeReason.approvedWithCondition]. Bei `10` ist nachweislich Geld
///   geflossen, nur nicht der volle Betrag.
/// - **Keine oder keine brauchbare Antwort des Hosts** (Zeitueberschreitung,
///   Netzfehler, Antwort nicht pruefbar): `hostUncertain` und
///   [HpsCode.sendReversal] -- laut hobex (16.09.2026) wird dann ein Storno
///   nachgeschickt, siehe `HpsPayments`.
/// - Codes **anderer TECS-Produkte** (Webservices, mPOS, TecsWeb, SEPA,
///   Verbraucher-Plattform) stehen mit ihrem Titel hier, damit der Nachweis
///   sie benennt -- aber als `noStatement`: am HPS-Zahlweg sagen sie nichts
///   ueber eine Kartenzahlung.
library;

import 'response_codes.dart';

// Bewusst eine Zeile je Code: so bleibt die Tabelle neben der Liste von
// hobex lesbar, und ein neuer Code ist ein Eintrag mehr.
// dart format off

/// Die TECS-Codes ausser den gemessenen, in der Reihenfolge der Liste.
/// Teil von [HpsCodes.all].
const List<HpsCode> tecsCodes = <HpsCode>[
  // -- ISO-8583-Antworten des Hosts --
  HpsCode.tecs('1', 'Refer to Issuer', 'Host-Ablehnung: Rueckfrage beim Kartenherausgeber verlangt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('2', 'Call AS call number', 'Host-Ablehnung: Rueckruf bei der Autorisierungsstelle verlangt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('3', 'Invalid merchant number', 'Host-Ablehnung: Haendlernummer ungueltig; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.acquirerSetup),
  HpsCode.tecs('4', 'Retain card', 'Host-Ablehnung: Karte einziehen; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardBlocked),
  HpsCode.tecs('5', 'declined', 'Host-Ablehnung ohne naehere Angabe; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('6', 'Error', 'Host-Ablehnung wegen eines Fehlers -- der Host hat geantwortet und nicht genehmigt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('7', 'Pick up card, special condition', 'Host-Ablehnung: Karte einziehen (Sonderfall); nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardBlocked),
  HpsCode.tecs('8', 'Honor with idetification', 'Genehmigung gegen Ausweis -- eine Genehmigung, aber nicht "0"; ob das Terminal sie abgeschlossen hat, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.approvedWithCondition),
  HpsCode.tecs('9', 'Request in progress', 'Anfrage laeuft beim Host noch -- kein Endstand; ob belastet wird, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostTimeout, sendReversal: true),
  HpsCode.tecs('10', 'Approved for partial amount', 'nur ueber einen Teilbetrag genehmigt -- es ist Geld geflossen, aber nicht der volle Betrag', HpsCodeEffect.hostUncertain, HpsCodeReason.approvedWithCondition),
  HpsCode.tecs('11', 'VIP Approval', 'VIP-Genehmigung -- eine Genehmigung, aber nicht "0"; ob das Terminal sie abgeschlossen hat, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.approvedWithCondition),
  HpsCode.tecs('12', 'Invalid transaction', 'Host-Ablehnung: Vorgang ungueltig; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('13', 'Invalid amount', 'Host-Ablehnung: Betrag ungueltig; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.amountInvalid),
  HpsCode.tecs('14', 'Invalid card number', 'Host-Ablehnung: Kartennummer ungueltig; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('15', 'No such issuer', 'Host-Ablehnung: Kartenherausgeber unbekannt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('16', 'Approved, Update track 3', 'Genehmigung mit Spur-3-Aktualisierung -- eine Genehmigung, aber nicht "0"; ob das Terminal sie abgeschlossen hat, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.approvedWithCondition),
  HpsCode.tecs('17', 'Customer Cancellation', 'vom Kunden abgebrochen; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.aborted),
  HpsCode.tecs('18', 'Customer dispute', 'Host-Ablehnung: Kundenreklamation; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('19', 'Re-enter Transaction', 'Host-Ablehnung: Vorgang neu eingeben; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('20', 'Invalid Response', 'ungueltige Antwort im Hostverkehr -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('21', 'No action taken', 'Host: keine Aktion ausgefuehrt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('22', 'Suspected malfunction', 'vermutete Stoerung im Hostverkehr -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('23', 'Unacceptable transaction fee', 'Host-Ablehnung: Gebuehr nicht akzeptiert; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('24', 'File upd not supported by rcvr', 'Dateiaktualisierung nicht unterstuetzt -- betrifft keine Zahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('25', 'Unable to locate record', 'Datensatz nicht gefunden -- keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.noStatement),
  HpsCode.tecs('26', 'Duplicate file update record', 'doppelter Aktualisierungssatz -- betrifft keine Zahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('27', 'File update field edit error', 'Feldfehler bei Dateiaktualisierung -- betrifft keine Zahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('28', 'File temporarily unavailable', 'Datei voruebergehend nicht verfuegbar -- betrifft keine Zahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('29', 'File update not successful', 'Dateiaktualisierung gescheitert -- betrifft keine Zahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('30', 'Invalid format', 'Host-Ablehnung: Nachrichtenformat ungueltig; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('31', 'Issuer sign-off', 'Kartenherausgeber abgemeldet; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostUnavailable),
  HpsCode.tecs('32', 'Completed partially', 'nur teilweise ausgefuehrt -- es kann Geld geflossen sein, aber nicht der volle Betrag', HpsCodeEffect.hostUncertain, HpsCodeReason.approvedWithCondition),
  HpsCode.tecs('33', 'Card expired', 'Host-Ablehnung: Karte abgelaufen; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardExpired),
  HpsCode.tecs('34', 'Suspicion of manipulation', 'Host-Ablehnung: Manipulationsverdacht; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardBlocked),
  HpsCode.tecs('35', 'Card acceptor contact Acquirer', 'Host-Ablehnung: Haendler soll hobex kontaktieren; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('36', 'Restricted Card', 'Host-Ablehnung: Karte eingeschraenkt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardBlocked),
  HpsCode.tecs('37', 'Card acceptor call acquirer', 'Host-Ablehnung: Haendler soll hobex anrufen; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('38', 'Allowed PIN tries exceeded', 'Host-Ablehnung: zulaessige PIN-Versuche ueberschritten; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.pinTriesExceeded),
  HpsCode.tecs('40', 'Invalid function', 'Host-Ablehnung: Funktion ungueltig; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('41', 'Pick up Card', 'Host-Ablehnung: Karte einziehen (verloren gemeldet); nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardBlocked),
  HpsCode.tecs('42', 'No universal account', 'Host-Ablehnung: kein passendes Konto; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('43', 'Stolen card, pick up', 'Host-Ablehnung: Karte gestohlen gemeldet; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardBlocked),
  HpsCode.tecs('44', 'No investment account', 'Host-Ablehnung: kein passendes Konto; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('51', 'Not sufficient funds', 'Host-Ablehnung: Konto nicht gedeckt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.insufficientFunds),
  HpsCode.tecs('52', 'No checking account', 'Host-Ablehnung: kein Girokonto; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('53', 'No savings account', 'Host-Ablehnung: kein Sparkonto; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('54', 'Expired card', 'Host-Ablehnung: Karte abgelaufen; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardExpired),
  HpsCode.tecs('56', 'Card not in authorizer database', 'Host-Ablehnung: Karte beim Autorisierer unbekannt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('57', 'Invalid card number Ref.', 'Host-Ablehnung: Vorgang fuer diese Karte nicht erlaubt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('58', 'Trxn not permitted to card', 'Host-Ablehnung: Vorgang fuer diese Karte nicht erlaubt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('59', 'suspected fraud', 'Host-Ablehnung: Betrugsverdacht; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardBlocked),
  HpsCode.tecs('60', 'Card acceptor conteact acquirer', 'Host-Ablehnung: Haendler soll hobex kontaktieren; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('61', 'Exceeds wihtdrawal limit', 'Host-Ablehnung: Verfuegungsrahmen ueberschritten; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.insufficientFunds),
  HpsCode.tecs('62', 'Restricted card', 'Host-Ablehnung: Karte eingeschraenkt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardBlocked),
  HpsCode.tecs('63', 'Security violation', 'Host-Ablehnung: Sicherheitsverstoss; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('64', 'Invalid Transaction amount', 'Host-Ablehnung: Betrag ungueltig; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.amountInvalid),
  HpsCode.tecs('65', 'Activity count exceeded', 'Host-Ablehnung: zu viele Vorgaenge auf der Karte; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.insufficientFunds),
  HpsCode.tecs('66', 'Card acceptor call acquirer', 'Host-Ablehnung: Haendler soll hobex anrufen; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('67', 'Card pick up at ATM', 'Host-Ablehnung: Karte einziehen; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardBlocked),
  HpsCode.tecs('68', 'Response received too late', 'Antwort des Kartenherausgebers kam zu spaet -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostTimeout, sendReversal: true),
  HpsCode.tecs('75', 'PIN entered incorrectly too often', 'Host-Ablehnung: PIN zu oft falsch; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.pinTriesExceeded),
  HpsCode.tecs('76', 'Previos message not found', 'vorherige Nachricht nicht gefunden -- keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.noStatement),
  HpsCode.tecs('77', 'PIN entry necessary', 'Host-Ablehnung: PIN-Eingabe erforderlich; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.pinRequired),
  HpsCode.tecs('80', 'Invalid date', 'Host-Ablehnung: Datum ungueltig; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('81', 'Message flow error', 'Fehler in der Nachrichtenfolge mit dem Host -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('82', 'Authorization center not available for 600 seconds', 'Autorisierungszentrale nicht erreichbar (600 s); nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostUnavailable),
  HpsCode.tecs('83', 'Authorization center not available for 300 seconds', 'Autorisierungszentrale nicht erreichbar (300 s); nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostUnavailable),
  HpsCode.tecs('86', 'PIN Validation not possible', 'Host-Ablehnung: PIN-Pruefung nicht moeglich; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('87', 'Purchase Amount Only, no Cash Back Allowed', 'Host-Ablehnung: Bargeldauszahlung nicht erlaubt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.amountInvalid),
  HpsCode.tecs('88', 'Cryptographic failure', 'Host-Ablehnung: Kryptografiefehler; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('89', 'Authentication failure', 'Host-Ablehnung: Authentisierung gescheitert; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('90', 'Cutoff is in process', 'Host im Tagesabschluss; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostUnavailable),
  HpsCode.tecs('91', 'Card issuer temporarily not reachable', 'Kartenherausgeber voruebergehend nicht erreichbar; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostUnavailable),
  HpsCode.tecs('92', 'The card type is not processed by the authorization center', 'Host-Ablehnung: Kartentyp wird nicht verarbeitet; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('93', 'Validation of law', 'Host-Ablehnung aus rechtlichen Gruenden; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('94', 'Data has been transmitted twice', 'Daten doppelt uebertragen -- ein erster Vorgang unter dieser Kennung kann belastet haben', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('95', 'Reconcile / Prepay transaction failed', 'Abstimmung gescheitert -- betrifft keine Zahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('96', 'Processing temporarily not possible', 'Verarbeitung voruebergehend nicht moeglich; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostUnavailable),
  HpsCode.tecs('97', 'Security breach - MAC check indicates error condition', 'Host-Ablehnung: MAC-Pruefung gescheitert; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('98', 'Date and time not plausible', 'Host-Ablehnung: Datum und Uhrzeit unplausibel; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('99', 'Error in PAC encryption detected', 'Host-Ablehnung: Fehler in der PIN-Verschluesselung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('117', 'Incorrect PIN', 'Host-Ablehnung: PIN falsch; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.wrongPin),
  // -- TECS-Backend --
  HpsCode.tecs('3018', 'Invalid Currency', 'Waehrung ungueltig -- Abweisung der Anfrage; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.requestRejected, rejectsRequest: true),
  HpsCode.tecs('3019', 'Invalid Terminal', 'Terminal ungueltig -- Abweisung der Anfrage; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.acquirerSetup, rejectsRequest: true),
  HpsCode.tecs('3021', 'Invalid Terminal Type', 'Terminaltyp ungueltig -- Abweisung der Anfrage; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.acquirerSetup, rejectsRequest: true),
  HpsCode.tecs('3030', 'Declined Offline transaction', 'Offline-Vorgang abgelehnt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardDeclined),
  HpsCode.tecs('3031', 'Compeletion Amout over CTLS Limit', 'Betrag ueber dem Kontaktlos-Limit; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.amountInvalid),
  HpsCode.tecs('3032', 'Invalid Refund password', 'Passwort fuer die Gutschrift falsch; nichts ausgezahlt', HpsCodeEffect.conclusive, HpsCodeReason.refundPassword),
  HpsCode.tecs('3033', 'IBAN should be entered manually', 'Lastschriftverfahren: IBAN manuell eingeben -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3034', 'entered IBAN not valid, try again', 'Lastschriftverfahren: IBAN ungueltig -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3035', 'Empty Request', 'leere Anfrage -- Abweisung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.requestRejected, rejectsRequest: true),
  HpsCode.tecs('3036', 'Unknown Error - Fallback Exception', 'unbekannter Fehler im Backend -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.internalError),
  HpsCode.tecs('3037', 'Unsupported transaction type', 'Vorgangstyp nicht unterstuetzt -- Abweisung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.requestRejected, rejectsRequest: true),
  HpsCode.tecs('3038', 'Invalid card data', 'Kartendaten ungueltig; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardReadFailed),
  HpsCode.tecs('3039', 'Fatal error - backend offline', 'Backend nicht erreichbar; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostUnavailable),
  HpsCode.tecs('3050', 'ATM/POS terminal number cannot be located', 'Terminalnummer unbekannt -- Abweisung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.acquirerSetup, rejectsRequest: true),
  HpsCode.tecs('3051', 'Issuer response not received by CUPS', 'UnionPay: keine Antwort des Kartenherausgebers -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostTimeout, sendReversal: true),
  HpsCode.tecs('3052', 'PIN Block Error', 'UnionPay: PIN-Block fehlerhaft; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('3053', 'Reversed internally: Successful transaction with fault', 'UnionPay: intern storniert; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.reversedByHost),
  HpsCode.tecs('3054', 'Account not found in Transfer-in side', 'UnionPay: Konto nicht gefunden; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('3055', 'Reversed internally: Successful transaction with fault', 'UnionPay: intern storniert; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.reversedByHost),
  HpsCode.tecs('3056', 'Reversed internally: Successful transaction with fault', 'UnionPay: intern storniert; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.reversedByHost),
  HpsCode.tecs('3057', 'Reversed internally: Successful transaction with fault', 'UnionPay: intern storniert; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.reversedByHost),
  HpsCode.tecs('3058', 'Security processing failure', 'UnionPay: Sicherheitsverarbeitung gescheitert; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('3059', 'No arrears (transaction receipt not printed)', 'UnionPay: Beleg nicht gedruckt -- keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3060', 'Illegal Status of Acquirer', 'UnionPay: Acquirer-Status unzulaessig; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.acquirerSetup),
  HpsCode.tecs('3061', 'Incorrect IIN', 'UnionPay: IIN falsch; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('3062', 'Reversed internally: UPI action code Y1', 'UnionPay: intern storniert (Y1); nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.reversedByHost),
  HpsCode.tecs('3063', 'Reversed internally: UPI action code Y3', 'UnionPay: intern storniert (Y3); nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.reversedByHost),
  HpsCode.tecs('3064', 'declined, UPI action code Z1', 'UnionPay: abgelehnt (Z1); nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('3065', 'declined, UPI action code Z3', 'UnionPay: abgelehnt (Z3); nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('3066', 'Items not on Bankbook beyond limit, declined', 'UnionPay: Limit ueberschritten; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.insufficientFunds),
  HpsCode.tecs('3531', 'ws: TMC-lite Merchant Login error -WEBSERVICEONLY', 'Webservice (TMC-lite) -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3532', 'ws: TMC-lite Merchant Login error -INACTIVEUSER', 'Webservice (TMC-lite) -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3533', 'ws: TMC-lite Merchant Login error -LOCKEDUSER', 'Webservice (TMC-lite) -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3534', 'ws: TMC-lite Merchant Login error -PASSWORDEXPIRED', 'Webservice (TMC-lite) -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3537', 'ws: TMC-lite Merchant Login error -Username / Password invalid', 'Webservice (TMC-lite) -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3539', 'ws: TMC-lite Merchant Login error - NOTOK - General Error', 'Webservice (TMC-lite) -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3547', 'ws: TMC-lite Change Password error - Username / Password invalid', 'Webservice (TMC-lite) -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3549', 'ws: TMC-lite Change Password error - General failure', 'Webservice (TMC-lite) -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3559', 'ws: TMC-lite Reset Password error - General failure', 'Webservice (TMC-lite) -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3569', 'ws: TMC-lite Send receipt error - General failure', 'Webservice (TMC-lite) -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3579', 'ws: TMC-lite Signiture error - General failure', 'Webservice (TMC-lite) -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3589', 'ws: TMC-lite Get/Set MobileTx error - General failure', 'Webservice (TMC-lite) -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3590', 'Template Webservice: Insertion Failure.', 'Webservice -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3596', 'SendSMS Webservice: This phone number is not valid.', 'SMS-Versand -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3597', 'SendSMS Webservice: Twilio could not send the message.', 'SMS-Versand -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3598', 'SendSMS Webservice: SimpleSMS could not send the message.', 'SMS-Versand -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3693', 'SendEmail Webservice: The template could not be found.', 'Mailversand -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3694', 'SendEmail Webservice: The template could not be parsed.', 'Mailversand -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3695', 'SendEmail Webservice: The template could not be processed.', 'Mailversand -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3696', 'SendEmail Webservice: This email address is not valid.', 'Mailversand -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3697', 'SendEmail Webservice: Mail could not be sent.', 'Mailversand -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3699', 'SendEmail Webservice: general failure', 'Mailversand -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('3993', 'Fallback not allowed (CAT)', 'Rueckfall auf Magnetstreifen nicht erlaubt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardReadFailed),
  HpsCode.tecs('3994', 'Fallback not allowed (DB)', 'Rueckfall auf Magnetstreifen nicht erlaubt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardReadFailed),
  HpsCode.tecs('3995', 'Maestro PreAuth Not Allowed - Declined', 'Vorautorisierung mit Maestro nicht erlaubt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.requestRejected, rejectsRequest: true),
  HpsCode.tecs('3996', 'Invalid TxDateTime  (TX merchant time to server time too long)', 'Uhrzeit des Terminals weicht zu weit ab; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('4000', 'tmcpconsumer: APPLICATION_CONFIGURATION_FAILED', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4001', 'tmcpconsumer: ACCESS_DENIED', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4002', 'tmcpconsumer: APPLICATION_ERROR', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4003', 'tmcpconsumer: ACCESS_FORBIDDEN', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4004', 'tmcpconsumer: APPLICATION_INPUT_ERROR', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4005', 'tmcpconsumer: INVALID_INPUT', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4006', 'tmcpconsumer: USERACCOUNTNOTFOUND', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4007', 'tmcpconsumer: TOKEN_NOT_VALID', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4011', 'tmcpconsumer: ACTIVATECARD_ACCOUNTNOTFOUND', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4012', 'tmcpconsumer: PAYMENTPROCESSING_FAILED', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4013', 'tmcpconsumer: PAYMENTPROCESSING_PARTIALLY_FAILED', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4020', 'tmcpconsumer: STARTPAYMENT_FAILED', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4021', 'tmcpconsumer: EXECUTEPAYMENT_FAILED', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4022', 'tmcpconsumer: SMSVERIFICATION_FAILED', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4023', 'tmcpconsumer: USERPROFILEUPDARE_FAILED', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4024', 'tmcpconsumer: SENDCONFIRMATIONSMS_FAILED', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4025', 'tmcpconsumer: GETUSERPROFILE_FAILED', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4026', 'tmcpconsumer: REGISTERNEWCONSUMER_FAILED', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4027', 'tmcpconsumer: CONFIRMUSERREGISTRATION_FAILED', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4028', 'tmcpconsumer: INVALIDCONFIRMATIONEMAIL', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4029', 'tmcpconsumer: EMAILCONFIRMATION_TIME_EXCEEDED', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4030', 'tmcpconsumer: SMSCONFIRMATION_TIME_EXCEEDED', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4060', 'tmcpconsumer: WAVECREST_AUTHENTICATION_FAILED', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4061', 'tmcpconsumer: WAVECREST_FAILED424', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4062', 'tmcpconsumer: WAVECREST_FAILED400', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4063', 'tmcpconsumer: WAVECREST_FAILED412', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4064', 'tmcpconsumer: WAVECREST_FAILED500', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('4065', 'tmcpconsumer: WAVECREST_FAILED_COMMUNICATION', 'Verbraucher-Plattform (tmcpconsumer) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('5127', 'Technical Error HSM', 'technischer Fehler im Sicherheitsmodul des Backends -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.internalError),
  HpsCode.tecs('5158', 'Invalid Tx Date Time', 'Datum/Uhrzeit des Vorgangs ungueltig; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('5256', 'HSM Communication error', 'Verbindungsfehler zum Sicherheitsmodul des Backends -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.internalError),
  HpsCode.tecs('5271', 'HSM: wrong key derivation data (config?)', 'Schluesselableitung falsch (Einrichtung) -- vor der Weiterleitung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.acquirerSetup),
  HpsCode.tecs('5272', 'Error recrypting PAC', 'PIN-Umschluesselung gescheitert -- vor der Weiterleitung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('5273', 'MAC calculation failed', 'MAC-Berechnung gescheitert -- vor der Weiterleitung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('5274', 'Error recalculating received MAC', 'MAC der Antwort nicht nachrechenbar -- die Antwort des Acquirers ist unbrauchbar, ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('5275', 'MAC received differs from recalculated value', 'MAC der Antwort weicht ab -- die Antwort des Acquirers ist unbrauchbar, ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('5276', 'Partial authorization not allowed', 'Teilgenehmigung nicht erlaubt -- der Kartenherausgeber hat einen Teilbetrag genehmigt, ob das zurueckgenommen ist, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('5277', 'Verification error acq response', 'Antwort des Acquirers fehlerhaft -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('5278', 'Invalid response from acquirer', 'Antwort des Acquirers ungueltig -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('6000', 'Risk Management - Process Tx failed', 'vom Risikomanagement abgewiesen; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('6001', 'Risk Management - Merchant checks failed', 'vom Risikomanagement abgewiesen (Haendlerpruefung); nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('6002', 'Risk Management - PSP checks failed', 'vom Risikomanagement abgewiesen (PSP-Pruefung); nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('6003', 'Risk Management - MC & PSP checks failed', 'vom Risikomanagement abgewiesen; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('7777', 'Transaction successful (MsgType 4 - Get User Data)', 'Nutzerdatenabfrage erfolgreich -- keine Zahlung, deshalb keine Aussage', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7001', 'TecsWeb: Cancel pressed by user', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7002', 'TecsWeb: Communication with TecsXML failed', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7005', 'TecsWeb: MPI Error', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7006', 'TecsWeb: User validation failed', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7007', 'TecsWeb: System error', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7008', 'TecsWeb: Unauthorized', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7009', 'TecsWeb: TokenIO access denied', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7010', 'TecsWeb: TokenIO error', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7011', 'TecsWeb: Reversal failed', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7012', 'TecsWeb: Reversal', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7013', 'TecsWeb: MPI2 Signature Mismatch', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7014', 'TecsWeb: MPI2 Signature Missing', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7015', 'TecsWeb: Signature Mismatch', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7016', 'TecsWeb: Invalid Parameter', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7017', 'TecsWeb: Invalid Merchant', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7018', 'TecsWeb: Blik payment error', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7019', 'TecsWeb: Blik payment incomplete error', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7020', 'TecsWeb: Blik payment configuration error', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7021', 'TecsWeb: Pay By Link payment error', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7022', 'TecsWeb: Pay By Link incomplete error', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7023', 'TecsWeb: MPI1 Fallback error', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7024', 'TecsWeb: MPI2 error', 'Online-Zahlung (TecsWeb) -- betrifft keine Kartenzahlung am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7100', 'UNKNOWN (all other clearing.status)', 'Clearingstatus -- keine Aussage ueber den Vorgang am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7101', 'CANCELLED (if clearing.status 4 (cancelled))', 'Clearingstatus -- keine Aussage ueber den Vorgang am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('7102', 'CLEARING_ERROR (if clearing.status 3 (error))', 'Clearingstatus -- keine Aussage ueber den Vorgang am Terminal', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  // -- TecsClient und PinPad --
  HpsCode.tecs('8001', 'Parsing error', 'Anfrage nicht lesbar -- Abweisung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.requestRejected, rejectsRequest: true),
  HpsCode.tecs('8002', 'Invalid message type', 'Nachrichtentyp ungueltig -- Abweisung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.requestRejected, rejectsRequest: true),
  HpsCode.tecs('8003', 'PinPad device error', 'Geraetefehler am PinPad; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.terminalFault),
  HpsCode.tecs('8004', 'Transaction canceled by PinPad', 'am PinPad abgebrochen; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.aborted),
  HpsCode.tecs('8005', 'Transaction declined by PinPad', 'vom PinPad abgelehnt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardDeclined),
  HpsCode.tecs('8006', 'Communication with TecsEngine failed', 'Verbindung zum Backend gescheitert -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('8007', 'Invalid card number', 'Kartennummer ungueltig; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardDeclined),
  HpsCode.tecs('8008', 'Technical cancellation failed', 'technische Stornierung gescheitert -- der Vorgang kann belastet sein', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('8009', 'Technical cancellation', 'technisch storniert -- das Terminal hat den Vorgang selbst zurueckgenommen; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostTimeoutReversed),
  HpsCode.tecs('8010', 'Invalid response code from TecsEngine', 'ungueltiger Antwortcode vom Backend -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('8011', 'Unable to read magswipe', 'Magnetstreifen nicht lesbar; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardReadFailed),
  HpsCode.tecs('8012', 'ECRNotif communication failed', 'Benachrichtigung an die Kasse gescheitert -- keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8013', 'PinPad not operable', 'PinPad nicht betriebsbereit; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.terminalFault),
  HpsCode.tecs('8014', 'PinPad Busy (Transaction in progress)', 'PinPad beschaeftigt -- die Anfrage wurde nicht angenommen; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.terminalBusy, rejectsRequest: true),
  HpsCode.tecs('8015', 'Invalid Transaction (Trying to abort not-in-progress tx)', 'Abbruch eines nicht laufenden Vorgangs -- Abweisung der Anfrage', HpsCodeEffect.conclusive, HpsCodeReason.notAbortable, rejectsRequest: true),
  HpsCode.tecs('8016', 'EMV completion failed', 'EMV-Abschluss nach der Hostantwort gescheitert -- ob belastet bleibt, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('8017', 'Connection to local network failed (or terminal in force offline mode)', 'keine Netzverbindung bzw. Offline-Betrieb erzwungen; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostUnavailable),
  HpsCode.tecs('8018', 'PinPad Ready  (PP status, resp to 9043)', 'Geraetestatus "bereit" -- kein Ergebnis eines Vorgangs', HpsCodeEffect.noStatement, HpsCodeReason.noStatement),
  HpsCode.tecs('8019', 'Waiting for card   (PP status, resp to 9043)', 'Geraetestatus "wartet auf Karte" -- kein Ergebnis eines Vorgangs', HpsCodeEffect.noStatement, HpsCodeReason.noStatement),
  HpsCode.tecs('8020', 'Card read successfully   (PP status, resp to 9043)', 'Geraetestatus "Karte gelesen" -- kein Ergebnis eines Vorgangs', HpsCodeEffect.noStatement, HpsCodeReason.noStatement),
  HpsCode.tecs('81xx', 'Parsing problem: Field No. xx', 'Feld xx der Anfrage nicht lesbar -- Abweisung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.requestRejected, rejectsRequest: true),
  HpsCode.tecs('8201', 'Maximum amount limit for offline transaction exceeded', 'offline: Betragsgrenze ueberschritten; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostUnavailable),
  HpsCode.tecs('8202', 'Maximum offline transaction count exceeded', 'offline: Hoechstzahl an Vorgaengen erreicht; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostUnavailable),
  HpsCode.tecs('8203', 'Communication failed: Invalid card (Terminal is in force offline mode and card is not allowed for offline)', 'offline: Karte offline nicht erlaubt; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostUnavailable),
  HpsCode.tecs('8500', 'mPOS: (PosMate) General Failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8501', 'mPOS: (Chip) Application Selection Failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8502', 'mPOS: (Chip) Initiate Application Processing Failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8503', 'mPOS: (Chip) Read Application Data Failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8504', 'mPOS: (Chip) Offline Data Authentication Failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8505', 'mPOS: (Chip) Process Restrictions Failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8506', 'mPOS: (Chip) Terminal Risk Management Failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8507', 'mPOS: (Chip) Cardholder Verification Method Failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8508', 'mPOS: (Chip) Terminal Action Analysis Failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8509', 'mPOS: (Chip) Card Action Analysis Failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8510', 'mPOS: (Chip) Completion Failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8511', 'mPOS: (EPOS) Transaction Terminated', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8512', 'mPOS: (Chip) No Answer to Reset', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8513', 'mPOS: (Swipe) Read Failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8514', 'mPOS: (Chip) Card Removed', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8515', 'mPOS: (PosMate) User Cancelled', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8516', 'mPOS: (Chip) No Supported Applications', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8517', 'mPOS: (Chip) Card Blocked', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8518', 'mPOS: (Chip) Read Failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8519', 'mPOS: (PosMate) User Time Out', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8520', 'mPOS: (PosMate) DUKPT Key Failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8521', 'mPOS: MK/SK Key Failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8522', 'mPOS: (Contactless) Not Allowed', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8523', 'mPOS: (Contactless) Aborted', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8530', 'mPOS: TMC-lite Merchant Login successful', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8531', 'mPOS: TMC-lite Merchant Login error - Webservice only user', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8532', 'mPOS: TMC-lite Merchant Login error - Inactive user', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8533', 'mPOS: TMC-lite Merchant Login error - Locked user', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8534', 'mPOS: TMC-lite Merchant Login error - Password expired', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8537', 'mPOS: TMC-lite Merchant Login error - Incorrect username', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8538', 'mPOS: TMC-lite Merchant Login error - Incorrect password', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8539', 'mPOS: TMC-lite Merchant Login error - General failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8540', 'mPOS: TMC-lite Change Password successful', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8547', 'mPOS: TMC-lite Change Password error - Incorrect username', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8548', 'mPOS: TMC-lite Change Password error - Incorrect password', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8549', 'mPOS: TMC-lite Change Password error - General failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8550', 'mPOS: TMC-lite Send Receipt successful', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8559', 'mPOS: TMC-lite Send Receipt error - General failure', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8560', 'mPOS: Communication with TMC-lite failed', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8561', 'mPOS: Communication with TUS failed', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8562', 'mPOS: SW upgrade filesystem error', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8563', 'mPOS: SW upgrade error', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8564', 'mPOS: Bluetooth connect error', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8565', 'mPOS: Logon error', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8566', 'mPOS: Invalid Amount', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8567', 'mPOS: Signature rejected', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8568', 'mPOS: Signature callback was not set', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8569', 'mPOS: Communication with TecsXML failed', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8570', 'mPOS: Technical cancellation has been sent', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8571', 'mPOS: Spm2 didn\'t respond within defined timeout to TCM', 'mPOS-Leser -- betrifft das HPS-Terminal nicht, keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('8809', 'TecsClientECRRest, TC communication failed.', 'Verbindung zwischen Kassenschnittstelle und Zahlungsanwendung gescheitert -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('8999', 'TecsClient/PinPad System error', 'Systemfehler der Zahlungsanwendung -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.internalError),
  // -- TECS-Verarbeitung --
  HpsCode.tecs('9001', 'Invalid Message received', 'Nachricht ungueltig -- Abweisung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.requestRejected, rejectsRequest: true),
  HpsCode.tecs('9004', 'Invalid Currency', 'Waehrung ungueltig -- Abweisung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.requestRejected, rejectsRequest: true),
  HpsCode.tecs('9005', 'Invalid Transaction Number', 'Vorgangsnummer ungueltig -- Abweisung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.requestRejected, rejectsRequest: true),
  HpsCode.tecs('9006', 'Technical error: Connection failed', 'Verbindung gescheitert -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('9007', 'Duplicate offline Tx', 'doppelter Offline-Vorgang -- ein erster Vorgang kann belastet haben', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('9008', 'Invalid Card Number', 'Kartennummer ungueltig; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardDeclined),
  HpsCode.tecs('9009', 'Invalid Terminal No', 'Terminalnummer ungueltig -- Abweisung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.acquirerSetup, rejectsRequest: true),
  HpsCode.tecs('9010', 'CVV/CVC2 must be present', 'Pruefziffer fehlt -- Abweisung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.requestRejected, rejectsRequest: true),
  HpsCode.tecs('9012', 'Invalid Amount', 'Betrag ungueltig; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.amountInvalid),
  HpsCode.tecs('9013', 'Invalid Acquirer', 'Acquirer ungueltig -- Abweisung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.acquirerSetup, rejectsRequest: true),
  HpsCode.tecs('9014', 'Invalid PIN', 'PIN falsch; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.wrongPin),
  HpsCode.tecs('9015', 'PIN retry exceeded', 'PIN zu oft falsch; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.pinTriesExceeded),
  HpsCode.tecs('9016', 'Invalid Product', 'Kartenprodukt nicht zugelassen; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.issuerDeclined),
  HpsCode.tecs('9017', 'Limit exceeded', 'Limit ueberschritten; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.insufficientFunds),
  HpsCode.tecs('9018', 'Card in the Blacklist', 'Karte gesperrt (Sperrliste); nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.cardBlocked),
  HpsCode.tecs('9019', 'Invalid ECR Data', 'Kassendaten ungueltig -- Abweisung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.requestRejected, rejectsRequest: true),
  HpsCode.tecs('9020', 'Refund retry exceeded', 'zu viele Gutschriftversuche; nichts ausgezahlt', HpsCodeEffect.conclusive, HpsCodeReason.refundRejected),
  HpsCode.tecs('9021', 'Refund amount too high', 'Gutschriftbetrag zu hoch; nichts ausgezahlt', HpsCodeEffect.conclusive, HpsCodeReason.refundRejected),
  HpsCode.tecs('9022', 'Pending', 'Vorgang schwebt -- kein Endstand; ob belastet wird, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostTimeout, sendReversal: true),
  HpsCode.tecs('9023', 'Cancel Denied, TX already cleared', 'Aufhebung abgelehnt, bereits abgerechnet -- die Zahlung bleibt belastet', HpsCodeEffect.conclusive, HpsCodeReason.cancelDenied),
  HpsCode.tecs('9024', 'Invalid IBAN: format error', 'Lastschriftverfahren: IBAN ungueltig -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('9025', 'Iban Blacklisted', 'Lastschriftverfahren: IBAN gesperrt -- betrifft keine Kartenzahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('9026', 'Amount Limit Reached', 'Betragsgrenze erreicht; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.amountInvalid),
  HpsCode.tecs('9028', 'Declined, Refund already performed', 'Gutschrift bereits ausgefuehrt; nichts erneut ausgezahlt', HpsCodeEffect.conclusive, HpsCodeReason.refundRejected),
  HpsCode.tecs('9029', 'TIP amount missing', 'Trinkgeldbetrag fehlt -- Abweisung; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.requestRejected, rejectsRequest: true),
  HpsCode.tecs('9031', 'Cancellation of Refund not allowed', 'Aufhebung einer Gutschrift nicht erlaubt -- die Gutschrift bleibt bestehen', HpsCodeEffect.conclusive, HpsCodeReason.requestRejected, rejectsRequest: true),
  HpsCode.tecs('9032', 'Declined (completed only partially), reversed automatically', 'nur teilweise ausgefuehrt und automatisch storniert; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.reversedByHost),
  HpsCode.tecs('9033', 'Original TX declined - cannot cancel (cancelling a declined transaction is forbidden)', 'Originalzahlung war abgelehnt, nichts aufzuheben -- als Antwort auf eine Aufhebung keine Aussage "weiterhin belastet"', HpsCodeEffect.noStatement, HpsCodeReason.originalDeclined),
  HpsCode.tecs('9034', 'Cardholder Initiated Transaction Not Found', 'Bezugsvorgang nicht gefunden -- keine Aussage ueber den Vorgang', HpsCodeEffect.noStatement, HpsCodeReason.noStatement),
  HpsCode.tecs('9096', 'Invalid TxDateTime  (TX merchant time to server time too long)', 'Uhrzeit des Terminals weicht zu weit ab; nichts belastet', HpsCodeEffect.conclusive, HpsCodeReason.hostRejected),
  HpsCode.tecs('9222', 'Offline Tx Cancellation Denied', 'Aufhebung eines Offline-Vorgangs abgelehnt -- die Zahlung bleibt belastet', HpsCodeEffect.conclusive, HpsCodeReason.cancelDenied),
  HpsCode.tecs('9901', 'Technical error: Internal application error', 'interner Anwendungsfehler im Backend -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.internalError),
  HpsCode.tecs('9902', 'Technical Error: Database', 'Datenbankfehler im Backend -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.internalError),
  HpsCode.tecs('9905', 'Acquirer Timeout', 'Zeitueberschreitung beim Acquirer -- ob belastet wurde, ist offen; laut hobex Storno nachschicken', HpsCodeEffect.hostUncertain, HpsCodeReason.hostTimeout, sendReversal: true),
  HpsCode.tecs('9906', 'Technical Error: Network error', 'Netzwerkfehler zum Acquirer -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('9907', 'Technical Error: Network error', 'Netzwerkfehler zum Acquirer -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('9908', 'Technical Error: Time Out received from acquirer', 'Zeitueberschreitung vom Acquirer gemeldet (im Betrieb 11.09.2026, TID 3556988) -- laut hobex (16.09.2026) ein Timeout wie jeder andere, Storno nachschicken', HpsCodeEffect.hostUncertain, HpsCodeReason.hostTimeout, sendReversal: true),
  HpsCode.tecs('9909', 'Technical Error: Disconnect received from acquirer', 'Verbindungsabbruch vom Acquirer gemeldet -- ob belastet wurde, ist offen', HpsCodeEffect.hostUncertain, HpsCodeReason.hostFault, sendReversal: true),
  HpsCode.tecs('30091', 'TerminalService: INVALID_Input', 'Terminalverwaltung (TerminalService) -- betrifft keine Zahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('30093', 'TerminalService: WRONG_TERMINAL_PASSWORD', 'Terminalverwaltung (TerminalService) -- betrifft keine Zahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('30094', 'TerminalService: INVALID_TERMINAL_NO', 'Terminalverwaltung (TerminalService) -- betrifft keine Zahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('30095', 'TerminalService: PAN_REF_NO_NOT_FOUND', 'Terminalverwaltung (TerminalService) -- betrifft keine Zahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('30096', 'TerminalService: UnexpectedExceptionOccurred', 'Terminalverwaltung (TerminalService) -- betrifft keine Zahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
  HpsCode.tecs('30099', 'TerminalService: INVALID_CREDENTIALS', 'Terminalverwaltung (TerminalService) -- betrifft keine Zahlung', HpsCodeEffect.noStatement, HpsCodeReason.technicalError),
];
